### PR TITLE
Add `=` operator

### PR DESCRIPTION
**Pull request by donno2048**
The unimplemented assignment operator is being used a lot which is bad practice

### CODE REVIEW

**Comment by tonybaloney** [comment]
thanks @donno2048 please see the compilation errors in CI

**Review by tonybaloney — APPROVED** [review]
